title: smylebifa
repository: smyledev/smyledev.github.io
author:        samoilov ilia
url:           "https://smyledev.github.io/"
theme:         jekyll-theme-hacker
description: Samoilov Ilia
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - "jekyll-github-metadata"

source: source
