title:         "Portfolio"
header_title:  "Portfolio"
author:        ilia samoilov
description:   "Portfolio"
baseurl:       ""
url:           "https://smylebifa.github.io/"

theme:         jekyll-theme-hacker