title: smylebifa
repository: smylebifa/smylebifa.github.io
author:        samoilov ilia
url:           "https://smylebifa.github.io/"
theme:         jekyll-theme-hacker
description: Cоздано с помощью jekyll, тема - hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - "jekyll-github-metadata"

source: source
