title: smyle_bifa
repository: smylebifa/smylebifa.github.io
author:        samoilov ilia
url:           "https://smylebifa.github.io/"
theme:         jekyll-theme-hacker
description:  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - "jekyll-github-metadata"

google_analytics: 317225230
