title:         "Портфолио"
header_title:  "Портфолио"
author:        ilia samoilov
description:   "Самойлов Илья"
baseurl:       ""
url:           "https://smylebifa.github.io/"

theme:         jekyll-theme-hacker